services:
  mysql:
    image: mysql:8.4
    container_name: matchmaking-backend-mysql
    environment:
      MYSQL_DATABASE: matchmaking-backend
      MYSQL_USER: matchmaking_user
      MYSQL_PASSWORD: matchmaking_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - matchmaking-backend-mysql:/var/lib/mysql

volumes:
  matchmaking-backend-mysql:
