services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: matchmaking-backend-qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - matchmaking-backend-qdrant:/qdrant/storage

volumes:
  matchmaking-backend-mysql:
  matchmaking-backend-qdrant:
